name: x509_plus
description: Dart library for parsing and working with X.509 certificates.
version: 0.3.3
homepage: https://github.com/Bdaya-Dev/x509
funding:
  - https://github.com/sponsors/rbellens

environment:
  sdk: ^3.0.0

dependencies:
  asn1lib: ^1.0.0
  collection: ^1.14.13
  crypto_keys_plus: ^0.5.0

dev_dependencies:
  lints: ^2.0.0
  melos: ^3.1.1
  test: ^1.0.0

false_secrets:
  - test/files/*
