name: x509
description: Dart library for parsing and working with X.509 certificates.
version: 0.1.2+1
homepage: https://github.com/appsup-dart/x509

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  asn1lib: ^0.6.0
  quiver: ^2.0.0
  crypto_keys: ^0.1.3

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
